[scenario]
include = "./scenarios.toml"

#[scenario.defs]
#W = 95.0
#C = 5.0
#D = -4.0
##
#[[scenario.list]]
## Cold scenario
#name = "C"
#epoch = 2050
#precip = "D"

[areas]
include = "./areas.toml"

[variables]
include = "./variables.toml"

[data]
include = "./data.toml"

[cmip]
include = "./cmip.toml"

[extra_data]
include = "./extra_data.toml"

[statistics]
include = "./statistics.toml"

[resampling]
include = "./resampling.toml"

[plotting]
include = "./plotting.toml"
