
[scenario]

[scenario.defs]
# General definitions for a name or precip do not have to be commented out below, even if the corresponding
# scenarios further below are commented-out.

# percentile of CMIP tas for a given epoch that the 'W' and 'G' scenarios correspond to
W = 90.0
G = 10.0
# percent change in precipitation (times global tas increase) for 'L' and 'H' scenarios
L = 4.0
H = 8.0


# Scenarios to use.
# This defines only the names and epoch.
# Values (what G/W and L/H correspond to) are filled in below.
# Comment-out scenarios that are not to be used/calculated.
[scenario.G_L2050]
name = "G"
epoch = 2050
precip = "L"
[scenario.W_L2050]
name = "W"
epoch = 2050
precip = "L"
[scenario.G_H2050]
name = "G"
epoch = 2050
precip = "H"
[scenario.W_H2050]
name = "W"
epoch = 2050
precip = "H"
[scenario.G_L2085]
name = "G"
epoch = 2085
precip = "L"
[scenario.W_L2085]
name = "W"
epoch = 2085
precip = "L"
[scenario.G_H2085]
name = "G"
epoch = 2085
precip = "H"
[scenario.W_H2085]
name = "W"
epoch = 2085
precip = "H"
